package openmovies

import (
	"time"

	"cinembrot/model"
)

// GetCuratedOpenMovies returns curated Creative Commons and Public Domain movies with full 4K/1080p direct links
func GetCuratedOpenMovies() []model.Movie {
	dateSintel := time.Date(2010, 9, 27, 0, 0, 0, 0, time.Local)
	dateBBB := time.Date(2008, 4, 10, 0, 0, 0, 0, time.Local)
	dateTOS := time.Date(2012, 9, 26, 0, 0, 0, 0, time.Local)
	dateCosmos := time.Date(2015, 8, 10, 0, 0, 0, 0, time.Local)
	dateSpring := time.Date(2019, 4, 4, 0, 0, 0, 0, time.Local)
	dateCharge := time.Date(2022, 12, 15, 0, 0, 0, 0, time.Local)

	return []model.Movie{
		{
			Title:             "Sintel",
			OriginalTitle:     "Sintel (The Durian Open Movie Project)",
			Slug:              "sintel-2010",
			Type:              "movie",
			Status:            "released",
			Tagline:           "The dragon is not the monster.",
			Synopsis:          "A lonely young woman, Sintel, helps and befriends a wounded baby dragon whom she names Scales. But when Scales is snatched away by an adult dragon, Sintel embarks on a dangerous journey across land and ice to find her lost companion.",
			ReleaseDate:       &dateSintel,
			Year:              2010,
			DurationMinutes:   15,
			DurationFormatted: "15 min",
			Country:           "Netherlands",
			Language:          "English",
			AgeRating:         "13+",
			Quality:           "4K UHD BluRay",
			IsLegal:           true,
			IsFree:            true,
			LicenseType:       "Creative Commons",
			LicenseName:       "Creative Commons Attribution 3.0 (CC BY 3.0)",
			LicenseURL:        "https://creativecommons.org/licenses/by/3.0/",
			IMDbRating:        7.4,
			IMDbVotes:         15200,
			TMDbRating:        7.3,
			Rating:            7.4,
			VoteCount:         16000,
			Popularity:        45.2,
			Views:             8500000,
			PosterURL:         "https://upload.wikimedia.org/wikipedia/commons/8/8f/Sintel_poster.jpg",
			BackdropURL:       "https://durian.blender.org/wp-content/uploads/2010/09/sintel_4k_01.jpg",
			ThumbnailURL:      "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Sintel_poster.jpg/500px-Sintel_poster.jpg",
			TrailerURL:        "https://www.youtube.com/watch?v=eRsGyueVLvQ",
			SourceWebsite:     "durian.blender.org",
			SourceURL:         "https://durian.blender.org/download/",
			Genres: []model.Genre{
				{Name: "Animation", Slug: "animation"},
				{Name: "Fantasy", Slug: "fantasy"},
				{Name: "Adventure", Slug: "adventure"},
				{Name: "Short", Slug: "short"},
			},
			Directors: []model.Director{
				{Name: "Colin Levy", Slug: "colin-levy", PhotoURL: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Colin_Levy.jpg/500px-Colin_Levy.jpg"},
			},
			Actors: []model.Actor{
				{Name: "Halina Reijn", Slug: "halina-reijn", CharacterName: "Sintel (voice)"},
				{Name: "Thom Hoffman", Slug: "thom-hoffman", CharacterName: "Shaman (voice)"},
			},
			DownloadLinks: []model.DownloadLink{
				{
					Provider:   "Blender Foundation Direct",
					Quality:    "4K UHD 2160p (Surround 5.1)",
					Resolution: "4096x1744",
					FileSize:   "4.2 GB",
					Format:     "MKV",
					URL:        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
				},
				{
					Provider:   "Internet Archive",
					Quality:    "1080p Full HD",
					Resolution: "1920x818",
					FileSize:   "850 MB",
					Format:     "MP4",
					URL:        "https://archive.org/download/Sintel/sintel-2048-surround.mp4",
				},
			},
			StreamLinks: []model.StreamLink{
				{
					Provider:   "Blender Open Player",
					ServerName: "Official 4K Stream",
					Quality:    "4K UHD",
					EmbedURL:   "https://www.youtube.com/embed/eRsGyueVLvQ",
					DirectURL:  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
				},
			},
		},
		{
			Title:             "Big Buck Bunny",
			OriginalTitle:     "Big Buck Bunny (Peach Project)",
			Slug:              "big-buck-bunny-2008",
			Type:              "movie",
			Status:            "released",
			Tagline:           "A giant rabbit with a heart bigger than himself.",
			Synopsis:          "A large and lovable rabbit deals with bullying forest creatures who ruthlessly harass smaller animals, leading to a hilarious and inventive revenge plot.",
			ReleaseDate:       &dateBBB,
			Year:              2008,
			DurationMinutes:   10,
			DurationFormatted: "10 min",
			Country:           "Netherlands",
			Language:          "None / Music",
			AgeRating:         "SU / All Ages",
			Quality:           "4K UHD 60FPS",
			IsLegal:           true,
			IsFree:            true,
			LicenseType:       "Creative Commons",
			LicenseName:       "Creative Commons Attribution 3.0 (CC BY 3.0)",
			LicenseURL:        "https://creativecommons.org/licenses/by/3.0/",
			IMDbRating:        7.1,
			IMDbVotes:         19400,
			TMDbRating:        7.0,
			Rating:            7.1,
			VoteCount:         20500,
			Popularity:        38.4,
			Views:             12000000,
			PosterURL:         "https://upload.wikimedia.org/wikipedia/commons/c/c5/Big_buck_bunny_poster_big.jpg",
			BackdropURL:       "https://peach.blender.org/wp-content/uploads/bbb-splash.png",
			ThumbnailURL:      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/500px-Big_buck_bunny_poster_big.jpg",
			TrailerURL:        "https://www.youtube.com/watch?v=YE7VzlLtp-4",
			SourceWebsite:     "peach.blender.org",
			SourceURL:         "https://peach.blender.org/download/",
			Genres: []model.Genre{
				{Name: "Animation", Slug: "animation"},
				{Name: "Comedy", Slug: "comedy"},
				{Name: "Family", Slug: "family"},
				{Name: "Short", Slug: "short"},
			},
			Directors: []model.Director{
				{Name: "Sacha Goedegebure", Slug: "sacha-goedegebure"},
			},
			DownloadLinks: []model.DownloadLink{
				{
					Provider:   "Blender Foundation",
					Quality:    "4K UHD 60fps",
					Resolution: "3840x2160",
					FileSize:   "640 MB",
					Format:     "MP4",
					URL:        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
				},
				{
					Provider:   "Internet Archive",
					Quality:    "1080p FHD",
					Resolution: "1920x1080",
					FileSize:   "220 MB",
					Format:     "MP4",
					URL:        "https://archive.org/download/BigBuckBunny_124/BigBuckBunny_1080p.mp4",
				},
			},
			StreamLinks: []model.StreamLink{
				{
					Provider:   "HTML5 Direct Player",
					ServerName: "Google Cloud Fast Stream",
					Quality:    "1080p",
					EmbedURL:   "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
					DirectURL:  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
				},
			},
		},
		{
			Title:             "Tears of Steel",
			OriginalTitle:     "Tears of Steel (Mango Open Movie Project)",
			Slug:              "tears-of-steel-2012",
			Type:              "movie",
			Status:            "released",
			Tagline:           "Explore a dystopian future where humanity and cybernetic warriors collide.",
			Synopsis:          "Set in a dystopian future in Amsterdam, a group of scientists and soldiers attempt to save the world from an army of giant destructive robots by staging a crucial memory replay on a bridge.",
			ReleaseDate:       &dateTOS,
			Year:              2012,
			DurationMinutes:   12,
			DurationFormatted: "12 min",
			Country:           "Netherlands",
			Language:          "English",
			AgeRating:         "13+",
			Quality:           "4K UHD HDR",
			IsLegal:           true,
			IsFree:            true,
			LicenseType:       "Creative Commons",
			LicenseName:       "Creative Commons Attribution 3.0 (CC BY 3.0)",
			LicenseURL:        "https://creativecommons.org/licenses/by/3.0/",
			IMDbRating:        6.5,
			IMDbVotes:         8200,
			TMDbRating:        6.4,
			Rating:            6.5,
			VoteCount:         8900,
			Popularity:        28.0,
			Views:             4200000,
			PosterURL:         "https://upload.wikimedia.org/wikipedia/commons/0/07/Tears_of_Steel_poster.jpg",
			BackdropURL:       "https://mango.blender.org/wp-content/uploads/2012/09/01_render_00001.png",
			ThumbnailURL:      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Tears_of_Steel_poster.jpg/500px-Tears_of_Steel_poster.jpg",
			TrailerURL:        "https://www.youtube.com/watch?v=R6MlUcmOul8",
			SourceWebsite:     "mango.blender.org",
			SourceURL:         "https://mango.blender.org/download/",
			Genres: []model.Genre{
				{Name: "Science Fiction", Slug: "science-fiction"},
				{Name: "Action", Slug: "action"},
				{Name: "Short", Slug: "short"},
			},
			Directors: []model.Director{
				{Name: "Ian Hubert", Slug: "ian-hubert"},
			},
			Actors: []model.Actor{
				{Name: "Derek de Lint", Slug: "derek-de-lint", CharacterName: "Old Thom"},
				{Name: "Sergio Hasselbaink", Slug: "sergio-hasselbaink", CharacterName: "Barley"},
			},
			DownloadLinks: []model.DownloadLink{
				{
					Provider:   "Blender Foundation",
					Quality:    "4K UHD (Surround 7.1)",
					Resolution: "4096x1714",
					FileSize:   "3.5 GB",
					Format:     "MKV",
					URL:        "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
				},
			},
			StreamLinks: []model.StreamLink{
				{
					Provider:   "Fast Stream Player",
					ServerName: "Official Stream",
					Quality:    "1080p",
					EmbedURL:   "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
					DirectURL:  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
				},
			},
		},
		{
			Title:             "Cosmos Laundromat",
			OriginalTitle:     "Cosmos Laundromat: First Cycle",
			Slug:              "cosmos-laundromat-2015",
			Type:              "movie",
			Status:            "released",
			Tagline:           "On a desolate island, a suicidal sheep meets his quirky fate.",
			Synopsis:          "On a desolate island, a suicidal sheep named Franck meets a mysterious salesman named Victor, who offers him the gift of a lifetime: the chance to live different lives in parallel dimensions.",
			ReleaseDate:       &dateCosmos,
			Year:              2015,
			DurationMinutes:   12,
			DurationFormatted: "12 min",
			Country:           "Netherlands",
			Language:          "English",
			AgeRating:         "13+",
			Quality:           "4K UHD HDR",
			IsLegal:           true,
			IsFree:            true,
			LicenseType:       "Creative Commons",
			LicenseName:       "Creative Commons Attribution 4.0 (CC BY 4.0)",
			LicenseURL:        "https://creativecommons.org/licenses/by/4.0/",
			IMDbRating:        7.2,
			IMDbVotes:         5300,
			TMDbRating:        7.1,
			Rating:            7.2,
			VoteCount:         6000,
			Popularity:        24.5,
			Views:             3500000,
			PosterURL:         "https://upload.wikimedia.org/wikipedia/commons/1/18/Cosmos_Laundromat_Poster.jpg",
			BackdropURL:       "https://gooseberry.blender.org/wp-content/uploads/2015/08/Cosmos-Laundromat-Poster-Horizontal.jpg",
			ThumbnailURL:      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Cosmos_Laundromat_Poster.jpg/500px-Cosmos_Laundromat_Poster.jpg",
			TrailerURL:        "https://www.youtube.com/watch?v=Y-rmzh0PI3c",
			SourceWebsite:     "gooseberry.blender.org",
			SourceURL:         "https://gooseberry.blender.org/",
			Genres: []model.Genre{
				{Name: "Animation", Slug: "animation"},
				{Name: "Sci-Fi", Slug: "sci-fi"},
				{Name: "Fantasy", Slug: "fantasy"},
				{Name: "Short", Slug: "short"},
			},
			Directors: []model.Director{
				{Name: "Mathieu Auvray", Slug: "mathieu-auvray"},
			},
			Actors: []model.Actor{
				{Name: "Pierre Bokma", Slug: "pierre-bokma", CharacterName: "Franck (voice)"},
				{Name: "Reinout Scholten van Aschat", Slug: "reinout-scholten", CharacterName: "Victor (voice)"},
			},
			DownloadLinks: []model.DownloadLink{
				{
					Provider:   "Blender Foundation",
					Quality:    "4K UHD (Surround 5.1)",
					Resolution: "3840x2160",
					FileSize:   "1.8 GB",
					Format:     "MKV",
					URL:        "https://archive.org/download/CosmosLaundromat/Cosmos%20Laundromat%20-%20First%20Cycle%20-%20Full%20HD.mp4",
				},
			},
			StreamLinks: []model.StreamLink{
				{
					Provider:   "YouTube Embed",
					ServerName: "Official Blender Stream",
					Quality:    "4K UHD",
					EmbedURL:   "https://www.youtube.com/embed/Y-rmzh0PI3c",
				},
			},
		},
		{
			Title:             "Spring",
			OriginalTitle:     "Spring (Blender Open Movie)",
			Slug:              "spring-2019",
			Type:              "movie",
			Status:            "released",
			Tagline:           "The poetic dance of nature and rebirth.",
			Synopsis:          "Spring is the story of a shepherd girl and her dog, who face ancient spirits in order to continue the cycle of life. This poetic and visually stunning short film was directed by Andy Goralczyk.",
			ReleaseDate:       &dateSpring,
			Year:              2019,
			DurationMinutes:   8,
			DurationFormatted: "8 min",
			Country:           "Netherlands",
			Language:          "None / Music",
			AgeRating:         "SU / All Ages",
			Quality:           "4K UHD HDR 60fps",
			IsLegal:           true,
			IsFree:            true,
			LicenseType:       "Creative Commons",
			LicenseName:       "Creative Commons Attribution 4.0 (CC BY 4.0)",
			LicenseURL:        "https://creativecommons.org/licenses/by/4.0/",
			IMDbRating:        7.6,
			IMDbVotes:         3100,
			TMDbRating:        7.5,
			Rating:            7.6,
			VoteCount:         3500,
			Popularity:        32.1,
			Views:             9200000,
			PosterURL:         "https://upload.wikimedia.org/wikipedia/commons/e/e9/Spring_-_animated_short_film_poster.jpg",
			BackdropURL:       "https://cloud.blender.org/static/images/spring/spring_header.jpg",
			ThumbnailURL:      "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Spring_-_animated_short_film_poster.jpg/500px-Spring_-_animated_short_film_poster.jpg",
			TrailerURL:        "https://www.youtube.com/watch?v=WhWc3b3KhnY",
			SourceWebsite:     "studio.blender.org",
			SourceURL:         "https://studio.blender.org/films/spring/",
			Genres: []model.Genre{
				{Name: "Animation", Slug: "animation"},
				{Name: "Fantasy", Slug: "fantasy"},
				{Name: "Short", Slug: "short"},
			},
			Directors: []model.Director{
				{Name: "Andy Goralczyk", Slug: "andy-goralczyk"},
			},
			DownloadLinks: []model.DownloadLink{
				{
					Provider:   "Blender Studio Direct",
					Quality:    "4K UHD 60fps",
					Resolution: "3840x2160",
					FileSize:   "1.2 GB",
					Format:     "MP4",
					URL:        "https://archive.org/download/spring-open-movie/Spring_4k_60fps.mp4",
				},
			},
			StreamLinks: []model.StreamLink{
				{
					Provider:   "YouTube Embed",
					ServerName: "Official Stream",
					Quality:    "4K UHD",
					EmbedURL:   "https://www.youtube.com/embed/WhWc3b3KhnY",
				},
			},
		},
		{
			Title:             "Charge",
			OriginalTitle:     "Charge (Blender Open Movie Project)",
			Slug:              "charge-2022",
			Type:              "movie",
			Status:            "released",
			Tagline:           "An old man, a battery robot, and a high-stakes standoff.",
			Synopsis:          "In an old dystopian factory, an elderly scavenger extracts valuable battery energy from dormant war machines until an unexpected security robot wakes up.",
			ReleaseDate:       &dateCharge,
			Year:              2022,
			DurationMinutes:   3,
			DurationFormatted: "3 min",
			Country:           "Netherlands",
			Language:          "English",
			AgeRating:         "13+",
			Quality:           "4K UHD Real-time",
			IsLegal:           true,
			IsFree:            true,
			LicenseType:       "Creative Commons",
			LicenseName:       "Creative Commons Attribution 4.0 (CC BY 4.0)",
			LicenseURL:        "https://creativecommons.org/licenses/by/4.0/",
			IMDbRating:        7.2,
			IMDbVotes:         1200,
			TMDbRating:        7.2,
			Rating:            7.2,
			VoteCount:         1500,
			Popularity:        19.8,
			Views:             2100000,
			PosterURL:         "https://studio.blender.org/media/films/charge/poster.jpg",
			BackdropURL:       "https://studio.blender.org/media/films/charge/header.jpg",
			TrailerURL:        "https://www.youtube.com/watch?v=UXqq0ZvbOnk",
			SourceWebsite:     "studio.blender.org",
			SourceURL:         "https://studio.blender.org/films/charge/",
			Genres: []model.Genre{
				{Name: "Animation", Slug: "animation"},
				{Name: "Action", Slug: "action"},
				{Name: "Cyberpunk", Slug: "cyberpunk"},
				{Name: "Short", Slug: "short"},
			},
			Directors: []model.Director{
				{Name: "Hjalti Hjalmarsson", Slug: "hjalti-hjalmarsson"},
			},
			DownloadLinks: []model.DownloadLink{
				{
					Provider:   "Blender Studio",
					Quality:    "4K UHD",
					Resolution: "3840x2160",
					FileSize:   "450 MB",
					Format:     "MP4",
					URL:        "https://archive.org/download/charge-blender-film/Charge_4K.mp4",
				},
			},
			StreamLinks: []model.StreamLink{
				{
					Provider:   "YouTube Embed",
					ServerName: "Official Stream",
					Quality:    "4K UHD",
					EmbedURL:   "https://www.youtube.com/embed/UXqq0ZvbOnk",
				},
			},
		},
	}
}
